name: ToBase64
description: A Flutter tool to convert files to base64 encoding.
version: 1.3.0+4

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.10
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.5
  desktop_drop: ^0.4.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
